# These are supported funding model platforms
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-on-your-repository

github: wild8highlander
custom: ['https://www.buymeacoffee.com/wild8highlander']
