---
# yamllint configuration
# https://yamllint.readthedocs.io
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.pre-commit-config.yaml'
  - 'CITATION.cff'

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
  comments-indentation: {}
  document-end:
    present: true
  document-start:
    present: true
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-value:
    forbid: false
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: {}
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: {}
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  padding: {}
  quoted-strings:
    quote-type: any
    required: false
  trailing-spaces: {}
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
